### ISSUE TITLE
[Question] What happens when a script fails halfway through?

### ISSUE THREAD

**Issue by adam-geisen** [pekspro/EF-Migrations-Script-Generator-Task#1]
I've had trouble in the past running idempotent scripts because even though half of the scripts might work, if there is an error the migrations still get marked as ran. The issue with this is that if I try to re-run the script it won't fail anymore even if it should because it completely skips the failed migration.

**Comment by pekspro** [comment]
This repository is probably not the right place for questions like this, but it’s interesting so I’m trying to help anyway :-)

Do you have some example when this could happen? I have personally not experienced this. One thing to notice is that there are no transactions defined in the migrations script. I guess it’s up to the engine that executes the migrations to take care of that. I’m using the task **Azure SQL Database Deployment** to apply migrations. I’m not sure that if that task applies each migration in one transaction.

**Comment by adam-geisen** [comment]
An example that I've recently come across is when you change a table's schema and then add an index. The schema change might be applied correctly, but the index could fail. In that case your initial script run would fail _and_ mark the migration as completed. 

I asked this on the Entity framework team's github and they said they'd look into it in the future. I just wanted to see if this library was fixing that issue or not. 

You can close this issue if you'd like. Thank you!

**Comment by pekspro** [comment]
Thanks for the info @adam-geisen . This was details I wasn’t aware of :-)
