### ISSUE TITLE
Feature request: Provide the configuration for a custom NuGet.config

### ISSUE THREAD

**Issue by dannyyy** [pekspro/EF-Migrations-Script-Generator-Task#13]
Hi,

I like to request a new feature. At the moment it's not feasible to use your task if the `NuGet.config` contains at least one private repository with authentication. Due to some misconception in the design of the whole NuGet tooling, NuGet cannot handle anything if one entry is not available even it's not involved in the action.

I request to provide an `--fileconfig` argument which can handle an alternative configuration file.
`dotnet tool install -g --fileconfig MyNuGet.config dotnet-ef`.

Thank you and cheers

**Comment by mateuszradny** [comment]
I have the same problem, is any progress with this issue?

**Comment by pekspro** [comment]
@mateuszradny, sorry but no I haven’t done anything with this yet. You could always run this command manually before using this task. When I have the time and energy I might add support for this :-)

**Comment by pekspro** [comment]
@dannyyy and @mateuszradny,  now there is a setting in the **Advanced** area to set the NuGet configuration file.
