### ISSUE TITLE
Idempotent scripts aren't really idempotent

### ISSUE THREAD

**Issue by Tonvengo** [pekspro/EF-Migrations-Script-Generator-Task#15]
Hi.
In a description it says that this script is idempotent. I saw that you are running migration with idempotent flag, which is not really idempotent according to this: [Ef core issue](https://github.com/dotnet/efcore/issues/10717).

**Comment by pekspro** [comment]
Thanks, that's interesting. I will read more about this the following weekend.

As a side note, in a project that I deploy in Azure pipelines I spin up a new server, copy a database from production and then run the migrations script to make sure that everything run without any errors. It makes me less scared when deploying to production :-).

**Comment by pekspro** [comment]
I have removed this from the documentation. I agree this is a problem but it’s out of scope for this project.
