### ISSUE TITLE
when i dont want to add --idempotent option?

### ISSUE THREAD

**Issue by smockgithub** [pekspro/EF-Migrations-Script-Generator-Task#17]

**Comment by pekspro** [comment]
Hi @smockgithub 
Sorry, I have totally missed this, did nit see this until today :-(

I thought that everyone want to use the `idempotent` option ;-) But I guess you have a point. I will try to remember this and add this as an option to next version whenever that comes :-)

**Comment by pekspro** [comment]
Now there is a setting in the **Advanced** area for controlling if the scripts should be idempotent.
