### ISSUE TITLE
Intermittent Error

### ISSUE THREAD

**Issue by tekinc** [pekspro/EF-Migrations-Script-Generator-Task#18]
I sometimes receive a "Microsoft.EntityFrameworkCore.Tools.CommandException: Build failed." when running this task. I'm building using 3.1.2. Any ideas why? 

Every other step in my build process succeeds.

**Comment by pekspro** [comment]
I haven't seen that error message before :-( Could some answer in this thread help you?

https://stackoverflow.com/questions/38961115/build-failed-on-database-first-scaffold-dbcontext
