### ISSUE TITLE
doesn't work when dbcontext is in a library project

### ISSUE THREAD

**Issue by kemmis** [pekspro/EF-Migrations-Script-Generator-Task#2]
please add a separate input to specify the startup project.

**Comment by pekspro** [comment]
Hi
I think that is already supported :-) Try to set the project path to the start-up project.

If it doesn’t work, just let me know. If it does work, I would gladly accept some advice how to make the GUI more understandable, I totally understand that this is not obvious :-)

**Comment by kemmis** [comment]
I believe I did try that. I looked at the code and it uses that project path for both the `--project` parameter and the `--startup-project` parameter. From what I can tell, yes, the  `--startup-project` parameter needs to be pointed to a project that references your DbContext library, and is an executable type of project. However, you still need to tell the ef migrations tool where it can find the DbContext, so the  `--project` parameter still needs to point to the library project that contains your DbContext class.

So I'd suggest adding a second input for the tool that lets you (optionally) specify a startup project path. Then have a conditional in the code that uses that intput value for the  `--startup-project`  parameter if the user has entered one.

**Comment by pekspro** [comment]
You definitely have a point. The funny thing is that I have my database context in a library and I’m only targeting the start-up project with the `--project`  and `--startup-project` parameters and it works well. It’s a bit strange, maybe I’m just lucky. I will do as you suggested and add an optional parameter for the start-up project.

**Comment by kemmis** [comment]
I wonder if it has to do with the fact that my library projects target .netstandard rather than an actual implementation (netcoreapp or full .net framework). Also, my dbcontexts are marked internal and only visible to the startup project.

**Comment by pekspro** [comment]
I’m also using .netstandard for all my database context libraries. Maybe it’s related to the visibility. I will investigate this in a day or two, I’m curious :-)

Either way, I have added this parameter and uploaded the changes to the market place. To get it updated I just clicked on **Get it free** on https://marketplace.visualstudio.com/items?itemName=pekspro.pekspro-efcore-migration-script-generator (it might be that it will be automatically updated, I’m not sure). I did make a quick test and I think it works. Could you give it a try?

**Comment by pekspro** [comment]
I did play around with a database context as internal in a library and make it explicit visible to the startup project (it’s now a part of the test project in this repository). But I couldn’t replicate the issue you had. It’s still puzzles me.

**Comment by kemmis** [comment]
I haven't had a chance to try your updated version, but I was able to put together an example that reproduces the issue: https://github.com/kemmis/EF.Migrations.Bug

You can run [this](https://github.com/kemmis/EF.Migrations.Bug/blob/master/script-migration-not-work.ps1) file to see how the command works when specifying only the executable project for both the startup project and the main project.

You can run [this](https://github.com/kemmis/EF.Migrations.Bug/blob/master/script-migration-works.ps1) file to see how the command works when specifying the startup executable project as the startup project, and the dbcontext's class library project as the main project.

**Comment by pekspro** [comment]
Thanks for the demo project, that was kind of you :-) Now I have a rough idea why this doesn’t work.
I dig into the source code of [Entity Framework](https://github.com/aspnet/EntityFrameworkCore), and when the generating script command is executing it searches for classes that implements `IDesignTimeDbContextFactory` in the assembly. So if you move your `RacingDesignTimeDbContextFactory` class to the `Bug.Data.EntityFramework.MigrationUtil` project, `script-migration-not-work` will work :-)

One thing that is interesting is that this is some way done automatically in a web application. If you just add 

            services.AddDbContext<RacingDbContext>(options =>
                options.UseSqlServer(Configuration.GetConnectionString("RacingDbContext")));

in a web application, you only need to reference the web application and not the library when generating migration scripts. I created I PR for your demo project if you are interested.

All this said, I guess this is somehow cheating :-) In the latest version of **Entity Framework Migration Script** generator you could define the startup project independently of the library project.

**Comment by kemmis** [comment]
Good work. I will try out the latest version of the script generator task when I get back to work later this week and let you know how it goes. Thanks!!

**Comment by kemmis** [comment]
The updated version works well! Thanks for making that change. I've created a pull request with some updates to the descriptions and helper-texts to make things maybe a bit more clear for users. Feel free to use it, or not. 

https://github.com/pekspro/EF-Migrations-Script-Generator-Task/pull/3

**Comment by kemmis** [comment]
@pekspro, I have a ef core build task I'm interested in building, but i'm
not sure where to start. Would you have a few minutes to talk about my idea
with me? Maybe you're interested. Please email me if you have a chance:
rafe [at] kemmis [dot] info.
