### ISSUE TITLE
overriding msbuild parameters

### ISSUE THREAD

**Issue by graphicsxp** [pekspro/EF-Migrations-Script-Generator-Task#21]
The task runs `dotnet msbuild` but in my case it fails because I have a conditional import in my csproj based on the current configuration :  

` 	<Import Project="C:\dev\proj\BuildResources\Nuget\nugetpacker.props" Condition="'$(Configuration)' == 'Debug'" />`  

Since the configuration when building on the server is `Release` this import should be ignored. But for that, I must specify the current configuration in the msbuild parameters, which is not possible here. 

Any way this could be added ?

**Comment by pekspro** [comment]
Hi @graphicsxp 
Sorry for the late answer. I have to admit I am not sure exactly what you are asking for :-) Normally the application is build before in separate tasks before the migrations script are generated. Are you able to do that?

**Comment by graphicsxp** [comment]
in the code, just add configuration as a input parameter :  
```
  let cmdPath = tl.which('dotnet');
            tool = tl.tool(cmdPath)
                .arg('ef')
                .arg('migrations')
                .arg('script')
                .arg('--idempotent')
                .arg('--project')
                .arg(projectpath as string)
                .arg('--startup-project')
                .arg(startupprojectpath as string)
                .arg('--output')
                .arg(targetfolder + '/' + databasecontext + '.sql')
                .arg('--context')
                .arg(databasecontext)
                .arg('--verbose')
                .arg('--configuration')
                .arg(configuration);

```

this is because in my csproj I have conditional import which will break dotnet ef migration if the correct configuration is not passed. Sorry my first post was very misleading.

**Comment by pekspro** [comment]
Thanks @graphicsxp, now I understand what you need :-) I will think about this, probably I add this in a future update.

**Comment by pekspro** [comment]
@graphicsxp, now there is a setting in the **Advanced** area for controlling the build configuration. Could you verify that this works?

**Comment by graphicsxp** [comment]
@pekspro I'm no longer generating scripts in the pipeline. But thanks, that could be useful for future use!
