### ISSUE TITLE
Out of the blue getting errors on Azurepipeline

### ISSUE THREAD

**Issue by Marcel0024** [pekspro/EF-Migrations-Script-Generator-Task#22]
![image](https://user-images.githubusercontent.com/14852157/88676265-28960100-d0ec-11ea-8872-2ac27dee0165.png)

Any ideas?

**Comment by pekspro** [comment]
That is strange. I updated the tool a few days ago, but I do not think this matter in this case. Which version do the logs says you are using? Version 0.0.51 is the latest version.

I am confused by the message: 

    Since you just installed the .Net Core SDK, you will need to reopen the Command Prompt window before running the tool you installed.

Do you have any logs from previous successful builds?

**Comment by Marcel0024** [comment]
Here:

[successfullbuild.txt](https://github.com/pekspro/EF-Migrations-Script-Generator-Task/files/4993474/successfullbuild.txt)

**Comment by pekspro** [comment]
That is also interesting. In that log **dotnet-ef** was installed without any requests of restarting the command prompt.

Which agent specification are you using? What happens if you try a different one?

Also, are you installing any .Net Core SDK in the pipeline?

**Comment by Marcel0024** [comment]
It was default. Changing the Agent pool to 'Azure pipelines' and agent specification to 'windows-2019' fixed it..
I guess something changed on Azure's side.

Thanks for the help!
