### ISSUE TITLE
Add support for --no-build

### ISSUE THREAD

**Issue by likemike91** [pekspro/EF-Migrations-Script-Generator-Task#24]
Are there any plans to support the --no-build flags when using that task?

**Comment by pekspro** [comment]
That is an interesting idea. I will have a look on that this weekend.

**Comment by likemike91** [comment]
If there's something I could assist, let me know 😉

**Comment by pekspro** [comment]
@likemike91, now the tool has been updated to version 0.0.52 that include a setting for this parameter. Could you give it a try?

**Comment by likemike91** [comment]
@pekspro Sorry for the delay. The --no-build option works like a charm ;-)

**Comment by likemike91** [comment]
@pekspro Sorry for the delay...

The --no-build option works like a charm ;-)
