### ISSUE TITLE
Deploying Stored Procedures via a script

### ISSUE THREAD

**Issue by doug-saganworks** [pekspro/EF-Migrations-Script-Generator-Task#29]
When deploying stored procedures via a SQL script, the Script Generator puts the SQL used to create the Stored Procedure inside of a SQL IF BEGIN/END block.  The issue with this is that this causes an error in SQL server in that you can't create/update a stored procedure inside of a IF block.

**Comment by pekspro** [comment]
This repository is just a wrapper for dotnet ef that is generating the migration script. So, I think it is better if you comment this on: https://github.com/dotnet/efcore. There are some issues already that might be related:

https://github.com/dotnet/efcore/issues/7681
https://github.com/dotnet/efcore/issues/22616
https://github.com/dotnet/efcore/issues/22613
