### ISSUE TITLE
.net 5 

### ISSUE THREAD

**Issue by laborZH** [pekspro/EF-Migrations-Script-Generator-Task#32]
Hi 

wil you plan update the Project up to .net 5 ?

Best Regards

**Comment by pekspro** [comment]
Hi
.NET 5 is already supported :-) Is there something that you are missing?

**Comment by laborZH** [comment]
Hi pekspro
Thank you for your answer.

Oh no, sorry, I was on our local devops marketplace and See the last Update was in year 2019, now I chekced again on right marketplace and the newest is 2021 sorry :)


Best regards from Zürich
