### ISSUE TITLE
Array Replacement

### ISSUE THREAD

**Issue by Akinnagbe** [pekspro/EF-Migrations-Script-Generator-Task#33]
I tried to replace something like this
 "IDPClientSettings/Scopes":["openid","profile","offline_access","api"],
it returned this

Transformation found: IDPClientSettings/Scopes: openid profile offline_access api

How can I fix that?

Thanks

**Comment by pekspro** [comment]
Hmm... I'm not sure :-) Are you doing this in an efcore-migration-script-generator task?

**Comment by Akinnagbe** [comment]
ohoh, I am sorry, I posted the issue in a wrong repo. Please ignore it.

Thanks
