### ISSUE TITLE
node 6 deprecation warning

### ISSUE THREAD

**Issue by robertsimmons** [pekspro/EF-Migrations-Script-Generator-Task#36]
Hi! Getting this warning now in our build pipeline.

##[warning]This task uses Node 6 execution handler, which will be deprecated soon. If you are the developer of the task - please consider the migration guideline to Node 10 handler - https://aka.ms/migrateTaskNode10. If you are the user - feel free to reach out to the owners of this task to proceed on migration.

The linked migration guide seems pretty simple. Do you think this is something you'll have time to fix, or should I try to find time to open a PR?

Or it might need to be a newer version of the task, but I'm not familiar with how ADO task creation works, honestly. I just know you can pick a version when configuring a task.

**Comment by pekspro** [comment]
Thanks for this request. I do not get this warning myself, but I guess that might depend on which agent version you are using to build your project.

Either way, I will have a look on this. Looks like an upgrade should be simple. Just give me some days :-)

**Comment by pekspro** [comment]
@robertsimmons, I have released a new version that I hope fix this. Can you try it? You need to update to version 1.* in your pipeline.

**Comment by robertsimmons** [comment]
@pekspro That got rid of the warning! However, it looks like we lost some parameters. In particular "StartMigration", which is something we're currently relying on.

**Comment by pekspro** [comment]
@robertsimmons, good that the warning is gone :-) I noticed myself that StartMigration was lost but I thought I fixed that in version 1.0.1 but it looked it didn't work :-( Will fix it later today.

**Comment by pekspro** [comment]
@robertsimmons, something went wrong during a merge, sorry about that. But now it should be fixed. Can you try again?

**Comment by rsaki78** [comment]
@pekspro  Thanks, I upgraded to latest version, warning is gone and nothing is missing

**Comment by robertsimmons** [comment]
@pekspro Thanks so much for quickly addressing this! Everything looks good on our end now! I'm going to close this.
