### ISSUE TITLE
It seems the Script Generator doesn't generate Script for DBContext Seeding?

### ISSUE THREAD

**Issue by billytsoi** [pekspro/EF-Migrations-Script-Generator-Task#4]
I find that the Code generator will generate scripts for migration
but can it also generate scirpt for DBcontext
It seems the Script Generator doesn't generate Script for DBContext Seeding?

https://docs.microsoft.com/en-us/ef/core/modeling/data-seeding

Please advise. Thanks a lot

**Comment by pekspro** [comment]
That is an interesting question! I’m not sure if this is possible so I will need to do some research. I’ll get back to you in a few days.

**Comment by pekspro** [comment]
Now I’ve played around with this and it seems to work :-). Please see the test application as a reference. Also note that you need to create a new migration (`dotnet ef migrations add...`) after you added seeding data in `OnModelCreating`.

**Comment by billytsoi** [comment]
Hey. Thanks a lot

Let me have a try.

Regards
Billy Tsoi
