### ISSUE TITLE
Console log message incorrect when version is supplied

### ISSUE THREAD

**Issue by swoodcock-iq** [pekspro/EF-Migrations-Script-Generator-Task#40]
When an `eftoolversion` is supplied, the console message is `Installing latest version of dotnet-ef as global tool.`
When an `eftoolversion` is not supplied, the console message is `Installing version undefined of dotnet-ef as global tool.`
These should be the other way around?
The eftoolversion is respected and supplied to the --version argument, so this is mostly cosmetic.

**Comment by pekspro** [comment]
Thanks, you are probably right! I might have a look on this next weekend :-)
