### ISSUE TITLE
FEATURE REQUEST: --no-transactions

### ISSUE THREAD

**Issue by cmbankester** [pekspro/EF-Migrations-Script-Generator-Task#44]
Add support for `--no-transactions` option

https://learn.microsoft.com/en-us/ef/core/cli/dotnet#dotnet-ef-migrations-script

**Comment by pekspro** [comment]
Thanks, I will have a look on that in a couple of days.

**Comment by pekspro** [comment]
@cmbankester, this is now added :-) 

![image](https://github.com/pekspro/EF-Migrations-Script-Generator-Task/assets/3163293/42e502ae-a7fa-4961-8185-bd61258804b9)
