### ISSUE TITLE
Error while running generated migration scripts between different SQL Azure databases

### ISSUE THREAD

**Issue by jaltenbernd** [pekspro/EF-Migrations-Script-Generator-Task#45]
Very odd error happening when I run a generated migration script against two different types of SQL Azure databases. 

My **Dev** box is a SQL Azure running on **General Purpose - Serverless: Gen5, 1 vCore**. When I run the migration it works great.

My **Prod** box is a SQL Azure running on **Hyperscale: Gen5, 2 vCores**. When I run the migration script it errors. The errors are from one migration that had deleted a couple database columns from a table. But, one prior migration was inserting data into those columns. So, for some reason, the Prod SQL Azure is validating the contents of an IF block in the migration script even though it will never run it. 

Have you ever had this happen?

**Comment by pekspro** [comment]
That sound very strange, nothing I have seen. Are you sure that the database schema is identical on the dev box and the prod box? You can compare these by generating a SQL script that creates the entire database, and then make sure that this script is identical on both servers. That how I do it, I guess there are better ways :-)

**Comment by jaltenbernd** [comment]
I agree. I have never seen this happen before. The schemas are identical on both machines. Even when I create a new emtpty database on the Prod server in Azure I can run the migration script once which works. Then for fun, I run the script again where it shouldn't do anything because all the migrations have been added to the EFMigration table. Once I run it again, boom, errors. 

But, if I do this same exercise on my Dev server in Azure, no issues. Very odd. 

I'll keep digging for answers. Thanks though. :)

**Comment by pekspro** [comment]
Good luck :-) I hope you solve, it is an interesting problem :-)

I'm closing this.
