### ISSUE TITLE
Add Verbose output flag

### ISSUE THREAD

**Issue by podgito** [pekspro/EF-Migrations-Script-Generator-Task#6]
Under the hood it seems you're using dotnet ef migrations script. Can you add the -v switch to output more detail. Or make this an option through the UI?

**Comment by pekspro** [comment]
Thanks for the suggestions. I must admin I wasn’t aware of that parameter :-) I guess it makes sense to add some kind of support for it. I’ll investigate it in a few days.

**Comment by pekspro** [comment]
Now I’ve updated this task so that the --verbose flag is always used on execution. I hope it works as expected :-)
